### ISSUE TITLE
Show something when entering secret key

### ISSUE THREAD

**Issue by ghost** [0x646e78/apicreds#6]
Presently this is blank.  It'd be nice to know that something is being entered. Maybe even showing the plaintext is not actually that bad.

**Comment by 0x646e78** [comment]
Closing out old issue I don't care enough about.

**Comment by 0x646e78** [comment]
Python's getpass() module which we use doesn't allow for anything to be echod. Generally it's not a great practice to display the number of characters also, due to the number of characters being seen. Probably fairly low risk of that tho.  but, it's been a couple of years and I don't have an easy answer while also using a simple library, so closing the issue.
